model:
  target: EquiformerV2    # Model class name in dipm.models
  num_layers: 8           # Model specific parameters
  num_rbf: 512            # Model specific parameters
  lmax: 4                 # Model specific parameters
  grid_resolution: 18     # Model specific parameters
  force_head: true        # Model specific parameters
  avg_num_neighbors: null # Default to Meta IS2RE value, so need to be overridden
  avg_num_nodes: null     # Same as above
  seed: 42                # Random seed for model initialization

dataset:
  train_dataset_paths: ./datasets/train      # Hdf5Reader
  valid_dataset_paths: ./datasets/val        # Hdf5Reader
  test_dataset_paths: ./datasets/test        # Hdf5Reader
  graph_cutoff_angstrom: 5.0                 # GraphDatasetBuilder
  batch_size: 16                             # GraphDatasetBuilder
  info_file: ./checkpoints/dataset_info.json # Skip info calculation if exists

train:
  num_epochs: 10                        # TrainingLoopConfig
  final_learning_rate: 1e-4             # OptimizerConfig
  dtype: bfloat16                       # Computation dtype in mixed precision training
  loss: MSELoss                         # Loss class name in dipm.loss
  local_model_output_dir: ./checkpoints # TrainingIOHandler
  restore_checkpoint_if_exists: true    # TrainingIOHandler
  restore_optimizer_state: true         # TrainingIOHandler
  save_path: ./equiformerv2.safetensors # Final save file name
  stage_splits: [0.7, 0.3]              # Two stage training
  energy_weights: [1.0, 25.0]           # Schedule for energy weight in stage 1 and 2
  forces_weights: [25.0, 1.0]           # Schedule for forces weight in stage 1 and 2
