model:
  # Create a model with hyperparameters
  target: EquiformerV2    # Model name in dipm.models.KNOWN_MODELS, both `EquiformerV2` or `equiformer_v2` are valid
  num_layers: 8           # Model specific parameters
  num_rbf: 512            # Model specific parameters
  lmax: 4                 # Model specific parameters
  grid_resolution: 18     # Model specific parameters
  force_head: true        # Model specific parameters
  avg_num_neighbors: null # Default to Meta IS2RE value, so need to be overridden
  avg_num_nodes: null     # Same as above
  seed: 42                # Random seed for model initialization, default to 42
  # Or use a pretrained model
  # pretrained: ./checkpoints/equiformerv2.safetensors
  # keep_force_head: false

dataset:
  train_dataset_paths: ./datasets/train      # Hdf5Reader
  valid_dataset_paths: ./datasets/val        # Hdf5Reader
  test_dataset_paths: ./datasets/test        # Hdf5Reader
  graph_cutoff_angstrom: 5.0                 # GraphDatasetBuilder
  batch_size: 16                             # GraphDatasetBuilder
  info_file: ./checkpoints/dataset_info.json # Skip info calculation if exists
  # Defined in GraphDatasetBuilder, the model will be updated accordingly, but only works with pretrained models
  # drop_unseen_elements: true

train:
  num_epochs: 10                        # TrainingLoopConfig
  final_learning_rate: 1e-4             # OptimizerConfig
  dtype: bfloat16                       # Computation dtype in mixed precision training
  loss: MSELoss                         # Loss name in dipm.loss.KNOWN_LOSSES, both `mse`, `mse_loss` or `MSELoss` are valid
  local_model_output_dir: ./checkpoints # TrainingIOHandler
  restore_checkpoint_if_exists: true    # TrainingIOHandler
  restore_optimizer_state: true         # TrainingIOHandler
  save_path: ./equiformerv2.safetensors # Final save file name
  stage_splits: [0.7, 0.3]              # Two stage training
  energy_weights: [1.0, 25.0]           # Schedule for energy weight in stage 1 and 2
  forces_weights: [25.0, 1.0]           # Schedule for forces weight in stage 1 and 2
  tensorboard: equiformerv2             # Project name for TensorBoard, logdir will be ./logs/project_name/datetime
  wandb: equiformerv2                   # Project name for Weights and Biases, logs will be in ./logs/project_name/
